name: sensor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip>=24
  - pip:
      - python-snap7==2.1.0
      - fastapi>=0.115,<1
      - uvicorn[standard]>=0.34,<1
      - pydantic>=2.10,<3
      - PyMySQL>=1.1,<2
      - cryptography==42.0.8
